here
:get-mime-type (s-s)
  [ $. s:index-of ] sip +
  '.ez       [ 'application/andrew-inset                                 ] s:case
  '.anx      [ 'application/annodex                                      ] s:case
  '.atomcat  [ 'application/atomcat+xml                                  ] s:case
  '.atomsrv  [ 'application/atomserv+xml                                 ] s:case
  '.atom     [ 'application/atom+xml                                     ] s:case
  '.lin      [ 'application/bbolin                                       ] s:case
  '.cu       [ 'application/cu-seeme                                     ] s:case
  '.davmount [ 'application/davmount+xml                                 ] s:case
  '.dcm      [ 'application/dicom                                        ] s:case
  '.tsp      [ 'application/dsptype                                      ] s:case
  '.es       [ 'application/ecmascript                                   ] s:case
  '.ttf      [ 'application/font-sfnt                                    ] s:case
  '.otf      [ 'application/font-sfnt                                    ] s:case
  '.pfr      [ 'application/font-tdpfr                                   ] s:case
  '.woff     [ 'application/font-woff                                    ] s:case
  '.spl      [ 'application/futuresplash                                 ] s:case
  '.gz       [ 'application/gzip                                         ] s:case
  '.hta      [ 'application/hta                                          ] s:case
  '.jar      [ 'application/java-archive                                 ] s:case
  '.js       [ 'application/javascript                                   ] s:case
  '.ser      [ 'application/java-serialized-object                       ] s:case
  '.class    [ 'application/java-vm                                      ] s:case
  '.json     [ 'application/json                                         ] s:case
  '.m3g      [ 'application/m3g                                          ] s:case
  '.hqx      [ 'application/mac-binhex40                                 ] s:case
  '.cpt      [ 'application/mac-compactpro                               ] s:case
  '.nbp      [ 'application/mathematica                                  ] s:case
  '.nb       [ 'application/mathematica                                  ] s:case
  '.mbox     [ 'application/mbox                                         ] s:case
  '.mdb      [ 'application/msaccess                                     ] s:case
  '.dot      [ 'application/msword                                       ] s:case
  '.doc      [ 'application/msword                                       ] s:case
  '.mxf      [ 'application/mxf                                          ] s:case
  '.bin      [ 'application/octet-stream                                 ] s:case
  '.oda      [ 'application/oda                                          ] s:case
  '.opf      [ 'application/oebps-package+xml                            ] s:case
  '.ogx      [ 'application/ogg                                          ] s:case
  '.onepkg   [ 'application/onenote                                      ] s:case
  '.onetmp   [ 'application/onenote                                      ] s:case
  '.onetoc2  [ 'application/onenote                                      ] s:case
  '.one      [ 'application/onenote                                      ] s:case
  '.pdf      [ 'application/pdf                                          ] s:case
  '.pgp      [ 'application/pgp-encrypted                                ] s:case
  '.key      [ 'application/pgp-keys                                     ] s:case
  '.sig      [ 'application/pgp-signature                                ] s:case
  '.prf      [ 'application/pics-rules                                   ] s:case
  '.eps3     [ 'application/postscript                                   ] s:case
  '.eps2     [ 'application/postscript                                   ] s:case
  '.epsf     [ 'application/postscript                                   ] s:case
  '.epsi     [ 'application/postscript                                   ] s:case
  '.eps      [ 'application/postscript                                   ] s:case
  '.ai       [ 'application/postscript                                   ] s:case
  '.ps       [ 'application/postscript                                   ] s:case
  '.rar      [ 'application/rar                                          ] s:case
  '.rdf      [ 'application/rdf+xml                                      ] s:case
  '.rtf      [ 'application/rtf                                          ] s:case
  '.stl      [ 'application/sla                                          ] s:case
  '.smil     [ 'application/smil+xml                                     ] s:case
  '.smi      [ 'application/smil+xml                                     ] s:case
  '.apk      [ 'application/vnd.android.package-archive                  ] s:case
  '.cdy      [ 'application/vnd.cinderella                               ] s:case
  '.udeb     [ 'application/vnd.debian.binary-package                    ] s:case
  '.ddeb     [ 'application/vnd.debian.binary-package                    ] s:case
  '.deb      [ 'application/vnd.debian.binary-package                    ] s:case
  '.sfd      [ 'application/vnd.font-fontforge-sfd                       ] s:case
  '.kml      [ 'application/vnd.google-earth.kml+xml                     ] s:case
  '.kmz      [ 'application/vnd.google-earth.kmz                         ] s:case
  '.xul      [ 'application/vnd.mozilla.xul+xml                          ] s:case
  '.xlam     [ 'application/vnd.ms-excel.addin.macroEnabled.12           ] s:case
  '.xlsb     [ 'application/vnd.ms-excel.sheet.binary.macroEnabled.12    ] s:case
  '.xlsm     [ 'application/vnd.ms-excel.sheet.macroEnabled.12           ] s:case
  '.xltm     [ 'application/vnd.ms-excel.template.macroEnabled.12        ] s:case
  '.xlt      [ 'application/vnd.ms-excel                                 ] s:case
  '.xlb      [ 'application/vnd.ms-excel                                 ] s:case
  '.xls      [ 'application/vnd.ms-excel                                 ] s:case
  '.eot      [ 'application/vnd.ms-fontobject                            ] s:case
  '.thmx     [ 'application/vnd.ms-officetheme                           ] s:case
  '.cat      [ 'application/vnd.ms-pki.seccat                            ] s:case
  '.pps      [ 'application/vnd.ms-powerpoint                            ] s:case
  '.ppt      [ 'application/vnd.ms-powerpoint                            ] s:case
  '.docm     [ 'application/vnd.ms-word.document.macroEnabled.12         ] s:case
  '.dotm     [ 'application/vnd.ms-word.template.macroEnabled.12         ] s:case
  '.odc      [ 'application/vnd.oasis.opendocument.chart                 ] s:case
  '.odb      [ 'application/vnd.oasis.opendocument.database              ] s:case
  '.odf      [ 'application/vnd.oasis.opendocument.formula               ] s:case
  '.odg      [ 'application/vnd.oasis.opendocument.graphics              ] s:case
  '.otg      [ 'application/vnd.oasis.opendocument.graphics-template     ] s:case
  '.odi      [ 'application/vnd.oasis.opendocument.image                 ] s:case
  '.odp      [ 'application/vnd.oasis.opendocument.presentation          ] s:case
  '.otp      [ 'application/vnd.oasis.opendocument.presentation-template ] s:case
  '.ods      [ 'application/vnd.oasis.opendocument.spreadsheet           ] s:case
  '.ots      [ 'application/vnd.oasis.opendocument.spreadsheet-template  ] s:case
  '.odm      [ 'application/vnd.oasis.opendocument.text-master           ] s:case
  '.odt      [ 'application/vnd.oasis.opendocument.text                  ] s:case
  '.ott      [ 'application/vnd.oasis.opendocument.text-template         ] s:case
  '.oth      [ 'application/vnd.oasis.opendocument.text-web              ] s:case
  '.cod      [ 'application/vnd.rim.cod                                  ] s:case
  '.mmf      [ 'application/vnd.smaf                                     ] s:case
  '.sdc      [ 'application/vnd.stardivision.calc                        ] s:case
  '.sds      [ 'application/vnd.stardivision.chart                       ] s:case
  '.sda      [ 'application/vnd.stardivision.draw                        ] s:case
  '.sdd      [ 'application/vnd.stardivision.impress                     ] s:case
  '.sdf      [ 'application/vnd.stardivision.math                        ] s:case
  '.sgl      [ 'application/vnd.stardivision.writer-global               ] s:case
  '.sdw      [ 'application/vnd.stardivision.writer                      ] s:case
  '.sxc      [ 'application/vnd.sun.xml.calc                             ] s:case
  '.stc      [ 'application/vnd.sun.xml.calc.template                    ] s:case
  '.sxd      [ 'application/vnd.sun.xml.draw                             ] s:case
  '.std      [ 'application/vnd.sun.xml.draw.template                    ] s:case
  '.sxi      [ 'application/vnd.sun.xml.impress                          ] s:case
  '.sti      [ 'application/vnd.sun.xml.impress.template                 ] s:case
  '.sxm      [ 'application/vnd.sun.xml.math                             ] s:case
  '.sxg      [ 'application/vnd.sun.xml.writer.global                    ] s:case
  '.sxw      [ 'application/vnd.sun.xml.writer                           ] s:case
  '.stw      [ 'application/vnd.sun.xml.writer.template                  ] s:case
  '.sis      [ 'application/vnd.symbian.install                          ] s:case
  '.pcap     [ 'application/vnd.tcpdump.pcap                             ] s:case
  '.cap      [ 'application/vnd.tcpdump.pcap                             ] s:case
  '.vss      [ 'application/vnd.visio                                    ] s:case
  '.vsw      [ 'application/vnd.visio                                    ] s:case
  '.vst      [ 'application/vnd.visio                                    ] s:case
  '.vsd      [ 'application/vnd.visio                                    ] s:case
  '.wbxml    [ 'application/vnd.wap.wbxml                                ] s:case
  '.wmlc     [ 'application/vnd.wap.wmlc                                 ] s:case
  '.wmlsc    [ 'application/vnd.wap.wmlscriptc                           ] s:case
  '.wp5      [ 'application/vnd.wordperfect5.1                           ] s:case
  '.wpd      [ 'application/vnd.wordperfect                              ] s:case
  '.wk       [ 'application/x-123                                        ] s:case
  '.7z       [ 'application/x-7z-compressed                              ] s:case
  '.abw      [ 'application/x-abiword                                    ] s:case
  '.dmg      [ 'application/x-apple-diskimage                            ] s:case
  '.bcpio    [ 'application/x-bcpio                                      ] s:case
  '.torrent  [ 'application/x-bittorrent                                 ] s:case
  '.cab      [ 'application/x-cab                                        ] s:case
  '.cbr      [ 'application/x-cbr                                        ] s:case
  '.cbz      [ 'application/x-cbz                                        ] s:case
  '.cda      [ 'application/x-cdf                                        ] s:case
  '.cdf      [ 'application/x-cdf                                        ] s:case
  '.vcd      [ 'application/x-cdlink                                     ] s:case
  '.pgn      [ 'application/x-chess-pgn                                  ] s:case
  '.mph      [ 'application/x-comsol                                     ] s:case
  '.cpio     [ 'application/x-cpio                                       ] s:case
  '.csh      [ 'application/x-csh                                        ] s:case
  '.udeb     [ 'application/x-debian-package                             ] s:case
  '.deb      [ 'application/x-debian-package                             ] s:case
  '.dxr      [ 'application/x-director                                   ] s:case
  '.dir      [ 'application/x-director                                   ] s:case
  '.dcr      [ 'application/x-director                                   ] s:case
  '.dms      [ 'application/x-dms                                        ] s:case
  '.wad      [ 'application/x-doom                                       ] s:case
  '.dvi      [ 'application/x-dvi                                        ] s:case
  '.pcf.Z    [ 'application/x-font-pcf                                   ] s:case
  '.pcf      [ 'application/x-font-pcf                                   ] s:case
  '.gsf      [ 'application/x-font                                       ] s:case
  '.pfb      [ 'application/x-font                                       ] s:case
  '.pfa      [ 'application/x-font                                       ] s:case
  '.mm       [ 'application/x-freemind                                   ] s:case
  '.spl      [ 'application/x-futuresplash                               ] s:case
  '.gan      [ 'application/x-ganttproject                               ] s:case
  '.gnumeric [ 'application/x-gnumeric                                   ] s:case
  '.sgf      [ 'application/x-go-sgf                                     ] s:case
  '.gcf      [ 'application/x-graphing-calculator                        ] s:case
  '.taz      [ 'application/x-gtar-compressed                            ] s:case
  '.tgz      [ 'application/x-gtar-compressed                            ] s:case
  '.gtar     [ 'application/x-gtar                                       ] s:case
  '.hdf      [ 'application/x-hdf                                        ] s:case
  '.xht      [ 'application/xhtml+xml                                    ] s:case
  '.xhtml    [ 'application/xhtml+xml                                    ] s:case
  '.hwp      [ 'application/x-hwp                                        ] s:case
  '.ica      [ 'application/x-ica                                        ] s:case
  '.info     [ 'application/x-info                                       ] s:case
  '.isp      [ 'application/x-internet-signup                            ] s:case
  '.ins      [ 'application/x-internet-signup                            ] s:case
  '.iii      [ 'application/x-iphone                                     ] s:case
  '.iso      [ 'application/x-iso9660-image                              ] s:case
  '.jam      [ 'application/x-jam                                        ] s:case
  '.jnlp     [ 'application/x-java-jnlp-file                             ] s:case
  '.jmz      [ 'application/x-jmol                                       ] s:case
  '.chrt     [ 'application/x-kchart                                     ] s:case
  '.kil      [ 'application/x-killustrator                               ] s:case
  '.skm      [ 'application/x-koan                                       ] s:case
  '.skt      [ 'application/x-koan                                       ] s:case
  '.skd      [ 'application/x-koan                                       ] s:case
  '.skp      [ 'application/x-koan                                       ] s:case
  '.kpt      [ 'application/x-kpresenter                                 ] s:case
  '.kpr      [ 'application/x-kpresenter                                 ] s:case
  '.ksp      [ 'application/x-kspread                                    ] s:case
  '.kwt      [ 'application/x-kword                                      ] s:case
  '.kwd      [ 'application/x-kword                                      ] s:case
  '.latex    [ 'application/x-latex                                      ] s:case
  '.lha      [ 'application/x-lha                                        ] s:case
  '.lyx      [ 'application/x-lyx                                        ] s:case
  '.lzh      [ 'application/x-lzh                                        ] s:case
  '.lzx      [ 'application/x-lzx                                        ] s:case
  '.fbdoc    [ 'application/x-maker                                      ] s:case
  '.book     [ 'application/x-maker                                      ] s:case
  '.fb       [ 'application/x-maker                                      ] s:case
  '.fm       [ 'application/x-maker                                      ] s:case
  '.frame    [ 'application/x-maker                                      ] s:case
  '.maker    [ 'application/x-maker                                      ] s:case
  '.frm      [ 'application/x-maker                                      ] s:case
  '.mif      [ 'application/x-mif                                        ] s:case
  '.xsd      [ 'application/xml                                          ] s:case
  '.xml      [ 'application/xml                                          ] s:case
  '.m3u8     [ 'application/x-mpegURL                                    ] s:case
  '.dll      [ 'application/x-msdos-program                              ] s:case
  '.bat      [ 'application/x-msdos-program                              ] s:case
  '.exe      [ 'application/x-msdos-program                              ] s:case
  '.com      [ 'application/x-msdos-program                              ] s:case
  '.msi      [ 'application/x-msi                                        ] s:case
  '.wmd      [ 'application/x-ms-wmd                                     ] s:case
  '.wmz      [ 'application/x-ms-wmz                                     ] s:case
  '.nc       [ 'application/x-netcdf                                     ] s:case
  '.pac      [ 'application/x-ns-proxy-autoconfig                        ] s:case
  '.nwc      [ 'application/x-nwc                                        ] s:case
  '.o        [ 'application/x-object                                     ] s:case
  '.oza      [ 'application/x-oz-application                             ] s:case
  '.p7r      [ 'application/x-pkcs7-certreqresp                          ] s:case
  '.crl      [ 'application/x-pkcs7-crl                                  ] s:case
  '.pyo      [ 'application/x-python-code                                ] s:case
  '.pyc      [ 'application/x-python-code                                ] s:case
  '.shx      [ 'application/x-qgis                                       ] s:case
  '.shp      [ 'application/x-qgis                                       ] s:case
  '.qgs      [ 'application/x-qgis                                       ] s:case
  '.qtl      [ 'application/x-quicktimeplayer                            ] s:case
  '.rdp      [ 'application/x-rdp                                        ] s:case
  '.rpm      [ 'application/x-redhat-package-manager                     ] s:case
  '.rss      [ 'application/x-rss+xml                                    ] s:case
  '.rb       [ 'application/x-ruby                                       ] s:case
  '.sce      [ 'application/x-scilab                                     ] s:case
  '.sci      [ 'application/x-scilab                                     ] s:case
  '.xcos     [ 'application/x-scilab-xcos                                ] s:case
  '.shar     [ 'application/x-shar                                       ] s:case
  '.swfl     [ 'application/x-shockwave-flash                            ] s:case
  '.swf      [ 'application/x-shockwave-flash                            ] s:case
  '.sh       [ 'application/x-sh                                         ] s:case
  '.scr      [ 'application/x-silverlight                                ] s:case
  '.xslt     [ 'application/xslt+xml                                     ] s:case
  '.xsl      [ 'application/xslt+xml                                     ] s:case
  '.xspf     [ 'application/xspf+xml                                     ] s:case
  '.sql      [ 'application/x-sql                                        ] s:case
  '.sitx     [ 'application/x-stuffit                                    ] s:case
  '.sit      [ 'application/x-stuffit                                    ] s:case
  '.sv4cpio  [ 'application/x-sv4cpio                                    ] s:case
  '.sv4crc   [ 'application/x-sv4crc                                     ] s:case
  '.tar      [ 'application/x-tar                                        ] s:case
  '.tcl      [ 'application/x-tcl                                        ] s:case
  '.gf       [ 'application/x-tex-gf                                     ] s:case
  '.texi     [ 'application/x-texinfo                                    ] s:case
  '.texinfo  [ 'application/x-texinfo                                    ] s:case
  '.pk       [ 'application/x-tex-pk                                     ] s:case
  '.sik      [ 'application/x-trash                                      ] s:case
  '.old      [ 'application/x-trash                                      ] s:case
  '.bak      [ 'application/x-trash                                      ] s:case
  '.%        [ 'application/x-trash                                      ] s:case
  '.~        [ 'application/x-trash                                      ] s:case
  '.man      [ 'application/x-troff-man                                  ] s:case
  '.me       [ 'application/x-troff-me                                   ] s:case
  '.ms       [ 'application/x-troff-ms                                   ] s:case
  '.roff     [ 'application/x-troff                                      ] s:case
  '.tr       [ 'application/x-troff                                      ] s:case
  '.t        [ 'application/x-troff                                      ] s:case
  '.ustar    [ 'application/x-ustar                                      ] s:case
  '.src      [ 'application/x-wais-source                                ] s:case
  '.wz       [ 'application/x-wingz                                      ] s:case
  '.crt      [ 'application/x-x509-ca-cert                               ] s:case
  '.xcf      [ 'application/x-xcf                                        ] s:case
  '.fig      [ 'application/x-xfig                                       ] s:case
  '.xpi      [ 'application/x-xpinstall                                  ] s:case
  '.xz       [ 'application/x-xz                                         ] s:case
  '.zip      [ 'application/zip                                          ] s:case
  '.amr      [ 'audio/amr                                                ] s:case
  '.awb      [ 'audio/amr-wb                                             ] s:case
  '.axa      [ 'audio/annodex                                            ] s:case
  '.snd      [ 'audio/basic                                              ] s:case
  '.au       [ 'audio/basic                                              ] s:case
  '.sco      [ 'audio/csound                                             ] s:case
  '.orc      [ 'audio/csound                                             ] s:case
  '.csd      [ 'audio/csound                                             ] s:case
  '.flac     [ 'audio/flac                                               ] s:case
  '.kar      [ 'audio/midi                                               ] s:case
  '.midi     [ 'audio/midi                                               ] s:case
  '.mid      [ 'audio/midi                                               ] s:case
  '.m4a      [ 'audio/mpeg                                               ] s:case
  '.mp3      [ 'audio/mpeg                                               ] s:case
  '.mp2      [ 'audio/mpeg                                               ] s:case
  '.mpega    [ 'audio/mpeg                                               ] s:case
  '.mpga     [ 'audio/mpeg                                               ] s:case
  '.m3u      [ 'audio/mpegurl                                            ] s:case
  '.spx      [ 'audio/ogg                                                ] s:case
  '.opus     [ 'audio/ogg                                                ] s:case
  '.ogg      [ 'audio/ogg                                                ] s:case
  '.oga      [ 'audio/ogg                                                ] s:case
  '.sid      [ 'audio/prs.sid                                            ] s:case
  '.aifc     [ 'audio/x-aiff                                             ] s:case
  '.aiff     [ 'audio/x-aiff                                             ] s:case
  '.aif      [ 'audio/x-aiff                                             ] s:case
  '.gsm      [ 'audio/x-gsm                                              ] s:case
  '.m3u      [ 'audio/x-mpegurl                                          ] s:case
  '.wax      [ 'audio/x-ms-wax                                           ] s:case
  '.wma      [ 'audio/x-ms-wma                                           ] s:case
  '.ram      [ 'audio/x-pn-realaudio                                     ] s:case
  '.rm       [ 'audio/x-pn-realaudio                                     ] s:case
  '.ra       [ 'audio/x-pn-realaudio                                     ] s:case
  '.ra       [ 'audio/x-realaudio                                        ] s:case
  '.pls      [ 'audio/x-scpls                                            ] s:case
  '.sd2      [ 'audio/x-sd2                                              ] s:case
  '.wav      [ 'audio/x-wav                                              ] s:case
  '.alc      [ 'chemical/x-alchemy                                       ] s:case
  '.cache    [ 'chemical/x-cache                                         ] s:case
  '.cac      [ 'chemical/x-cache                                         ] s:case
  '.csf      [ 'chemical/x-cache-csf                                     ] s:case
  '.ctab     [ 'chemical/x-cactvs-binary                                 ] s:case
  '.cascii   [ 'chemical/x-cactvs-binary                                 ] s:case
  '.cbin     [ 'chemical/x-cactvs-binary                                 ] s:case
  '.cdx      [ 'chemical/x-cdx                                           ] s:case
  '.cer      [ 'chemical/x-cerius                                        ] s:case
  '.c3d      [ 'chemical/x-chem3d                                        ] s:case
  '.chm      [ 'chemical/x-chemdraw                                      ] s:case
  '.cif      [ 'chemical/x-cif                                           ] s:case
  '.cmdf     [ 'chemical/x-cmdf                                          ] s:case
  '.cml      [ 'chemical/x-cml                                           ] s:case
  '.cpa      [ 'chemical/x-compass                                       ] s:case
  '.bsd      [ 'chemical/x-crossfire                                     ] s:case
  '.csm      [ 'chemical/x-csml                                          ] s:case
  '.csml     [ 'chemical/x-csml                                          ] s:case
  '.ctx      [ 'chemical/x-ctx                                           ] s:case
  '.cef      [ 'chemical/x-cxf                                           ] s:case
  '.cxf      [ 'chemical/x-cxf                                           ] s:case
  '.embl     [ 'chemical/x-embl-dl-nucleotide                            ] s:case
  '.emb      [ 'chemical/x-embl-dl-nucleotide                            ] s:case
  '.spc      [ 'chemical/x-galactic-spc                                  ] s:case
  '.gamin    [ 'chemical/x-gamess-input                                  ] s:case
  '.gam      [ 'chemical/x-gamess-input                                  ] s:case
  '.inp      [ 'chemical/x-gamess-input                                  ] s:case
  '.fchk     [ 'chemical/x-gaussian-checkpoint                           ] s:case
  '.fch      [ 'chemical/x-gaussian-checkpoint                           ] s:case
  '.cub      [ 'chemical/x-gaussian-cube                                 ] s:case
  '.gjf      [ 'chemical/x-gaussian-input                                ] s:case
  '.gjc      [ 'chemical/x-gaussian-input                                ] s:case
  '.gau      [ 'chemical/x-gaussian-input                                ] s:case
  '.gal      [ 'chemical/x-gaussian-log                                  ] s:case
  '.gcg      [ 'chemical/x-gcg8-sequence                                 ] s:case
  '.gen      [ 'chemical/x-genbank                                       ] s:case
  '.hin      [ 'chemical/x-hin                                           ] s:case
  '.ist      [ 'chemical/x-isostar                                       ] s:case
  '.istr     [ 'chemical/x-isostar                                       ] s:case
  '.dx       [ 'chemical/x-jcamp-dx                                      ] s:case
  '.jdx      [ 'chemical/x-jcamp-dx                                      ] s:case
  '.kin      [ 'chemical/x-kinemage                                      ] s:case
  '.mcm      [ 'chemical/x-macmolecule                                   ] s:case
  '.mmod     [ 'chemical/x-macromodel-input                              ] s:case
  '.mmd      [ 'chemical/x-macromodel-input                              ] s:case
  '.mol      [ 'chemical/x-mdl-molfile                                   ] s:case
  '.rd       [ 'chemical/x-mdl-rdfile                                    ] s:case
  '.rxn      [ 'chemical/x-mdl-rxnfile                                   ] s:case
  '.sdf      [ 'chemical/x-mdl-sdfile                                    ] s:case
  '.sd       [ 'chemical/x-mdl-sdfile                                    ] s:case
  '.tgf      [ 'chemical/x-mdl-tgf                                       ] s:case
  '.mcif     [ 'chemical/x-mmcif                                         ] s:case
  '.mol2     [ 'chemical/x-mol2                                          ] s:case
  '.b        [ 'chemical/x-molconn-Z                                     ] s:case
  '.gpt      [ 'chemical/x-mopac-graph                                   ] s:case
  '.zmt      [ 'chemical/x-mopac-input                                   ] s:case
  '.mpc      [ 'chemical/x-mopac-input                                   ] s:case
  '.mopcrt   [ 'chemical/x-mopac-input                                   ] s:case
  '.mop      [ 'chemical/x-mopac-input                                   ] s:case
  '.moo      [ 'chemical/x-mopac-out                                     ] s:case
  '.mvb      [ 'chemical/x-mopac-vib                                     ] s:case
  '.ent      [ 'chemical/x-ncbi-asn1-ascii                               ] s:case
  '.prt      [ 'chemical/x-ncbi-asn1-ascii                               ] s:case
  '.asn      [ 'chemical/x-ncbi-asn1                                     ] s:case
  '.aso      [ 'chemical/x-ncbi-asn1-binary                              ] s:case
  '.val      [ 'chemical/x-ncbi-asn1-binary                              ] s:case
  '.asn      [ 'chemical/x-ncbi-asn1-spec                                ] s:case
  '.ent      [ 'chemical/x-pdb                                           ] s:case
  '.pdb      [ 'chemical/x-pdb                                           ] s:case
  '.ros      [ 'chemical/x-rosdal                                        ] s:case
  '.sw       [ 'chemical/x-swissprot                                     ] s:case
  '.vms      [ 'chemical/x-vamas-iso14976                                ] s:case
  '.vmd      [ 'chemical/x-vmd                                           ] s:case
  '.xtel     [ 'chemical/x-xtel                                          ] s:case
  '.xyz      [ 'chemical/x-xyz                                           ] s:case
  '.gif      [ 'image/gif                                                ] s:case
  '.ief      [ 'image/ief                                                ] s:case
  '.jpg2     [ 'image/jp2                                                ] s:case
  '.jp2      [ 'image/jp2                                                ] s:case
  '.jpe      [ 'image/jpeg                                               ] s:case
  '.jpg      [ 'image/jpeg                                               ] s:case
  '.jpeg     [ 'image/jpeg                                               ] s:case
  '.jpm      [ 'image/jpm                                                ] s:case
  '.jpf      [ 'image/jpx                                                ] s:case
  '.jpx      [ 'image/jpx                                                ] s:case
  '.pcx      [ 'image/pcx                                                ] s:case
  '.png      [ 'image/png                                                ] s:case
  '.svgz     [ 'image/svg+xml                                            ] s:case
  '.svg      [ 'image/svg+xml                                            ] s:case
  '.tif      [ 'image/tiff                                               ] s:case
  '.tiff     [ 'image/tiff                                               ] s:case
  '.djv      [ 'image/vnd.djvu                                           ] s:case
  '.djvu     [ 'image/vnd.djvu                                           ] s:case
  '.ico      [ 'image/vnd.microsoft.icon                                 ] s:case
  '.wbmp     [ 'image/vnd.wap.wbmp                                       ] s:case
  '.cr2      [ 'image/x-canon-cr2                                        ] s:case
  '.crw      [ 'image/x-canon-crw                                        ] s:case
  '.ras      [ 'image/x-cmu-raster                                       ] s:case
  '.cdr      [ 'image/x-coreldraw                                        ] s:case
  '.pat      [ 'image/x-coreldrawpattern                                 ] s:case
  '.cdt      [ 'image/x-coreldrawtemplate                                ] s:case
  '.cpt      [ 'image/x-corelphotopaint                                  ] s:case
  '.erf      [ 'image/x-epson-erf                                        ] s:case
  '.art      [ 'image/x-jg                                               ] s:case
  '.jng      [ 'image/x-jng                                              ] s:case
  '.bmp      [ 'image/x-ms-bmp                                           ] s:case
  '.nef      [ 'image/x-nikon-nef                                        ] s:case
  '.orf      [ 'image/x-olympus-orf                                      ] s:case
  '.psd      [ 'image/x-photoshop                                        ] s:case
  '.pnm      [ 'image/x-portable-anymap                                  ] s:case
  '.pbm      [ 'image/x-portable-bitmap                                  ] s:case
  '.pgm      [ 'image/x-portable-graymap                                 ] s:case
  '.ppm      [ 'image/x-portable-pixmap                                  ] s:case
  '.rgb      [ 'image/x-rgb                                              ] s:case
  '.xbm      [ 'image/x-xbitmap                                          ] s:case
  '.xpm      [ 'image/x-xpixmap                                          ] s:case
  '.xwd      [ 'image/x-xwindowdump                                      ] s:case
  '.eml      [ 'message/rfc822                                           ] s:case
  '.iges     [ 'model/iges                                               ] s:case
  '.igs      [ 'model/iges                                               ] s:case
  '.silo     [ 'model/mesh                                               ] s:case
  '.mesh     [ 'model/mesh                                               ] s:case
  '.msh      [ 'model/mesh                                               ] s:case
  '.vrml     [ 'model/vrml                                               ] s:case
  '.wrl      [ 'model/vrml                                               ] s:case
  '.x3db     [ 'model/x3d+binary                                         ] s:case
  '.x3dv     [ 'model/x3d+vrml                                           ] s:case
  '.x3d      [ 'model/x3d+xml                                            ] s:case
  '.appcache [ 'text/cache-manifest                                      ] s:case
  '.icz      [ 'text/calendar                                            ] s:case
  '.ics      [ 'text/calendar                                            ] s:case
  '.css      [ 'text/css                                                 ] s:case
  '.csv      [ 'text/csv                                                 ] s:case
  '.323      [ 'text/h323                                                ] s:case
  '.shtml    [ 'text/html                                                ] s:case
  '.htm      [ 'text/html                                                ] s:case
  '.html     [ 'text/html                                                ] s:case
  '.uls      [ 'text/iuls                                                ] s:case
  '.mml      [ 'text/mathml                                              ] s:case
  '.srt      [ 'text/plain                                               ] s:case
  '.brf      [ 'text/plain                                               ] s:case
  '.pot      [ 'text/plain                                               ] s:case
  '.text     [ 'text/plain                                               ] s:case
  '.txt      [ 'text/plain                                               ] s:case
  '.asc      [ 'text/plain                                               ] s:case
  '.rml      [ 'text/plain                                               ] s:case
  '.md       [ 'text/plain                                               ] s:case
  '.rtx      [ 'text/richtext                                            ] s:case
  '.wsc      [ 'text/scriptlet                                           ] s:case
  '.sct      [ 'text/scriptlet                                           ] s:case
  '.tsv      [ 'text/tab-separated-values                                ] s:case
  '.tm       [ 'text/texmacs                                             ] s:case
  '.ttl      [ 'text/turtle                                              ] s:case
  '.vcard    [ 'text/vcard                                               ] s:case
  '.vcf      [ 'text/vcard                                               ] s:case
  '.jad      [ 'text/vnd.sun.j2me.app-descriptor                         ] s:case
  '.wmls     [ 'text/vnd.wap.wmlscript                                   ] s:case
  '.wml      [ 'text/vnd.wap.wml                                         ] s:case
  '.bib      [ 'text/x-bibtex                                            ] s:case
  '.boo      [ 'text/x-boo                                               ] s:case
  '.h        [ 'text/x-chdr                                              ] s:case
  '.hh       [ 'text/x-c++hdr                                            ] s:case
  '.hxx      [ 'text/x-c++hdr                                            ] s:case
  '.hpp      [ 'text/x-c++hdr                                            ] s:case
  '.h++      [ 'text/x-c++hdr                                            ] s:case
  '.htc      [ 'text/x-component                                         ] s:case
  '.csh      [ 'text/x-csh                                               ] s:case
  '.c        [ 'text/x-csrc                                              ] s:case
  '.cc       [ 'text/x-c++src                                            ] s:case
  '.cxx      [ 'text/x-c++src                                            ] s:case
  '.cpp      [ 'text/x-c++src                                            ] s:case
  '.c++      [ 'text/x-c++src                                            ] s:case
  '.patch    [ 'text/x-diff                                              ] s:case
  '.diff     [ 'text/x-diff                                              ] s:case
  '.d        [ 'text/x-dsrc                                              ] s:case
  '.hs       [ 'text/x-haskell                                           ] s:case
  '.java     [ 'text/x-java                                              ] s:case
  '.ly       [ 'text/x-lilypond                                          ] s:case
  '.lhs      [ 'text/x-literate-haskell                                  ] s:case
  '.moc      [ 'text/x-moc                                               ] s:case
  '.pas      [ 'text/x-pascal                                            ] s:case
  '.p        [ 'text/x-pascal                                            ] s:case
  '.gcd      [ 'text/x-pcs-gcd                                           ] s:case
  '.pm       [ 'text/x-perl                                              ] s:case
  '.pl       [ 'text/x-perl                                              ] s:case
  '.py       [ 'text/x-python                                            ] s:case
  '.scala    [ 'text/x-scala                                             ] s:case
  '.etx      [ 'text/x-setext                                            ] s:case
  '.sfv      [ 'text/x-sfv                                               ] s:case
  '.sh       [ 'text/x-sh                                                ] s:case
  '.tk       [ 'text/x-tcl                                               ] s:case
  '.tcl      [ 'text/x-tcl                                               ] s:case
  '.cls      [ 'text/x-tex                                               ] s:case
  '.sty      [ 'text/x-tex                                               ] s:case
  '.ltx      [ 'text/x-tex                                               ] s:case
  '.tex      [ 'text/x-tex                                               ] s:case
  '.vcs      [ 'text/x-vcalendar                                         ] s:case
  '.3gp      [ 'video/3gpp                                               ] s:case
  '.axv      [ 'video/annodex                                            ] s:case
  '.dl       [ 'video/dl                                                 ] s:case
  '.dv       [ 'video/dv                                                 ] s:case
  '.dif      [ 'video/dv                                                 ] s:case
  '.fli      [ 'video/fli                                                ] s:case
  '.gl       [ 'video/gl                                                 ] s:case
  '.ts       [ 'video/MP2T                                               ] s:case
  '.mp4      [ 'video/mp4                                                ] s:case
  '.mpe      [ 'video/mpeg                                               ] s:case
  '.mpg      [ 'video/mpeg                                               ] s:case
  '.mpeg     [ 'video/mpeg                                               ] s:case
  '.ogv      [ 'video/ogg                                                ] s:case
  '.mov      [ 'video/quicktime                                          ] s:case
  '.qt       [ 'video/quicktime                                          ] s:case
  '.mxu      [ 'video/vnd.mpegurl                                        ] s:case
  '.webm     [ 'video/webm                                               ] s:case
  '.flv      [ 'video/x-flv                                              ] s:case
  '.lsx      [ 'video/x-la-asf                                           ] s:case
  '.lsf      [ 'video/x-la-asf                                           ] s:case
  '.mkv      [ 'video/x-matroska                                         ] s:case
  '.mpv      [ 'video/x-matroska                                         ] s:case
  '.mng      [ 'video/x-mng                                              ] s:case
  '.asx      [ 'video/x-ms-asf                                           ] s:case
  '.asf      [ 'video/x-ms-asf                                           ] s:case
  '.avi      [ 'video/x-msvideo                                          ] s:case
  '.wmv      [ 'video/x-ms-wmv                                           ] s:case
  '.wm       [ 'video/x-ms-wm                                            ] s:case
  '.wmx      [ 'video/x-ms-wmx                                           ] s:case
  '.wvx      [ 'video/x-ms-wvx                                           ] s:case
  '.movie    [ 'video/x-sgi-movie                                        ] s:case
  '.ice      [ 'x-conference/x-cooltalk                                  ] s:case
  '.sisx     [ 'x-epoc/x-sisx-app                                        ] s:case
  '.wrl      [ 'x-world/x-vrml                                           ] s:case
  '.vrml     [ 'x-world/x-vrml                                           ] s:case
  '.vrm      [ 'x-world/x-vrml                                           ] s:case
  drop 'application/octet-stream ;
here swap - putn nl
